version: '3.8'

services:
  CoffeeQR:
    image: postgres:latest
    container_name: CoffeeQR
    environment:
      POSTGRES_DB: CoffeeQR
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: super
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_CoffeeQR:/var/lib/postgresql/data
    restart: unless-stopped
  
volumes:
  postgres_data_CoffeeQR:
